name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ['v*']

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          manifest-path: pyproject.toml
      - name: run unit tests
        run: |
          echo "running unit tests"
          pixi run test
      - name: build conda package
        run: |
          echo "build and verify conda package"
          pixi run verify-conda
